language: go

env:
  global:
  - GO111MODULE="on"

go:
  - 1.14.x
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install: true

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go mod vendor
  - go test -v -mod=readonly ./...

after_success:
  - go get -u -d github.com/spf13/hugo
  - cd $GOPATH/src/github.com/spf13/hugo && make && ./hugo -s docs && cd -

sudo: false
