name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.24.6']
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org

    steps:
      - name: Set up Go
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2

# the DataDog fork of this repository has many lint failures
#      - name: Lint
#        run: make lint

      - name: Test
        run: make test
